### ISSUE TITLE
Set up the Kanban board

### ISSUE THREAD

**Issue by Sboursen** [Sboursen/Rails-recipe-app#12]
# Description

Hi :wave: 

In this project, we are a team of two devs

We set up this project kanban board :point_right: [link](https://github.com/Sboursen/Rails-recipe-app/projects/1)

Cheers,

**Comment by elyor-doniyorov** [comment]
Hi @Sboursen and @mwafrika, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
✅ the GitHub issue link has been sent;
✅ there is a link to the GitHub project;
✅ there is information about the number of people in the group;


## Required Changes ♻️
- [ ] You have 1 unnecessary column which is `To be reviewed`. Please make sure you have added only the following 4 columns to the board:

* To Do
* In Progress
* In Review
* Done

- [ ] Your tasks 9 and 10 titles looks similar. Kindly give an appropriate title for task 10 which is related to creating navigation menu.

_Do not check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Sboursen** [comment]
Hi @elyor-doniyorov 

Thank you for the feedback :+1: 

Cheers,

**Comment by mikethreels** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Sboursen** [comment]
@mikethreels 

Thanks for the approval

Cheers,
